<script lang="ts">
    // Props
    interface Props {
        bodyCount: number;
        streak: number;
        userName?: string;
    }

    let { bodyCount, streak, userName = "OPERATIVE" }: Props = $props();

    // Determine status based on body count
    const status = $derived(
        bodyCount === 0
            ? "DORMANT"
            : bodyCount < 3
              ? "ACTIVE"
              : bodyCount < 5
                ? "LETHAL"
                : "JOHN WICK",
    );

    const date = new Date()
        .toLocaleDateString("en-US", {
            weekday: "long",
            year: "numeric",
            month: "long",
            day: "numeric",
        })
        .toUpperCase();
</script>

<!-- 
  Social Story Format (9:16 aspect ratio target)
  Fixed dimensions to ensure consistent output regardless of device screen size.
  1080x1920 is standard for Stories.
-->
<div
    id="mission-report-card"
    class="relative flex flex-col items-center justify-between text-center overflow-hidden bg-black text-neutral-200"
    style="width: 1080px; height: 1920px; font-family: 'JetBrains Mono', monospace;"
>
    <!-- Background Ambience -->
    <div
        class="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(20,20,20,1)_0%,rgba(0,0,0,1)_100%)]"
    ></div>
    <div
        class="absolute inset-0 opacity-20"
        style="background-image: repeating-linear-gradient(0deg, transparent, transparent 2px, #fff 2px, transparent 4px); background-size: 100% 8px;"
    ></div>

    <!-- Header -->
    <div class="z-10 mt-32 flex flex-col items-center gap-6">
        <div
            class="w-32 h-32 border-4 border-kl-gold rounded-full flex items-center justify-center"
        >
            <svg
                class="w-16 h-16 text-kl-gold"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
            >
                <path
                    stroke-linecap="round"
                    stroke-linejoin="round"
                    stroke-width="2"
                    d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"
                ></path>
            </svg>
        </div>
        <h1 class="text-6xl font-black tracking-[0.2em] text-kl-gold mt-8">
            MISSION REPORT
        </h1>
        <div class="h-1 w-64 bg-kl-gold"></div>
        <p class="text-3xl tracking-widest text-neutral-500 uppercase">
            {date}
        </p>
    </div>

    <!-- Main Stats -->
    <div class="z-10 flex flex-col items-center gap-4">
        <p class="text-4xl tracking-widest text-neutral-600 uppercase mb-4">
            CONFIRMED KILLS
        </p>
        <div class="text-[300px] leading-none font-bold text-white relative">
            {bodyCount}
            <!-- Decorative circles behind -->
            <div
                class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[500px] border border-neutral-800 rounded-full -z-10 opacity-50"
            ></div>
            <div
                class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] h-[700px] border border-neutral-900 rounded-full -z-10 opacity-30"
            ></div>
        </div>
    </div>

    <!-- Secondary Stats -->
    <div class="z-10 w-full px-32 grid grid-cols-2 gap-12 mt-12">
        <div
            class="border border-neutral-800 bg-neutral-900/50 p-12 backdrop-blur-sm"
        >
            <p class="text-2xl text-neutral-500 tracking-widest mb-4 uppercase">
                CURRENT STREAK
            </p>
            <p class="text-6xl font-bold text-white tracking-wider">
                {streak} <span class="text-3xl text-neutral-600">DAYS</span>
            </p>
        </div>
        <div
            class="border border-neutral-800 bg-neutral-900/50 p-12 backdrop-blur-sm"
        >
            <p class="text-2xl text-neutral-500 tracking-widest mb-4 uppercase">
                OPERATIVE STATUS
            </p>
            <p class="text-6xl font-bold text-kl-crimson tracking-wider">
                {status}
            </p>
        </div>
    </div>

    <!-- Footer -->
    <div class="z-10 mb-32 flex flex-col items-center gap-4 opacity-70">
        <p class="text-2xl tracking-[0.3em] uppercase text-neutral-600">
            GENERATED BY KILL LIST
        </p>
        <div class="text-xl tracking-widest text-neutral-700">KILLLIST.APP</div>
    </div>

    <!-- Corner Decorations -->
    <div
        class="absolute top-16 left-16 w-16 h-16 border-t-8 border-l-8 border-kl-gold"
    ></div>
    <div
        class="absolute top-16 right-16 w-16 h-16 border-t-8 border-r-8 border-kl-gold"
    ></div>
    <div
        class="absolute bottom-16 left-16 w-16 h-16 border-b-8 border-l-8 border-kl-gold"
    ></div>
    <div
        class="absolute bottom-16 right-16 w-16 h-16 border-b-8 border-r-8 border-kl-gold"
    ></div>
</div>
